### ISSUE TITLE
This wont build

### ISSUE THREAD

**Issue by Awire9966** [IonelPopJara/ascii-video-player#3]
This wont build so could you please prebuild it? thanks.

**Comment by Joshua-Noakes1** [comment]
Same as @Awire9966 can't get this to compile

**Comment by IonelPopJara** [comment]
You need to make sure to have OpenCV installed and configure the settings so that it works. Anyways, I'm gonna try building an executable during these days. Thanks for the comments!

**Comment by Awire9966** [comment]
No even then it doesnt work

**Comment by 0xxFF** [comment]
so what error did you get?

**Comment by LuckyScamper** [comment]
@Awire9966 @Dorikku @Joshua-Noakes1 you need to #include <thread> because one of the functions depends on it

**Comment by DarkOracle13** [comment]
![image](https://user-images.githubusercontent.com/74143543/173762370-aed3d96a-c04b-4160-8248-df606029ae82.png)
Hi, I have successfully installed the OpenCV installed, but it seems to be missing variables and namespaces and such?

**Comment by DarkOracle13** [comment]
> ![image](https://user-images.githubusercontent.com/74143543/173762370-aed3d96a-c04b-4160-8248-df606029ae82.png) Hi, I have successfully installed the OpenCV installed, but it seems to be missing variables and namespaces and such?

I have used the documentation from the CV API to fix the said problem, just needed to change it with some numbers instead, but another question, now I have linker problems? Any hints to solving this?

**Comment by IonelPopJara** [comment]
> > ![image](https://user-images.githubusercontent.com/74143543/173762370-aed3d96a-c04b-4160-8248-df606029ae82.png) Hi, I have successfully installed the OpenCV installed, but it seems to be missing variables and namespaces and such?
> 
> I have used the documentation from the CV API to fix the said problem, just needed to change it with some numbers instead, but another question, now I have linker problems? Any hints to solving this?

What standard are you using? And how did you configure the project settings on visual studio?

**Comment by Awire9966** [comment]
If anyone builds this reply with it pls

**Comment by IonelPopJara** [comment]
I added the executable file to the repo. Make sure to have the file you want to convert in the same folder. It worked for me so let me know if you were able to do it.

**Comment by Awire9966** [comment]
You forgot to add the dll files and stuff. I already did that.
The Player on my site: http://awiresoftware.xyz/mirrors/AsciiVideoPlayer/AsciiVideoPlayer.zip
Virus Scan: https://www.virustotal.com/gui/url/5708dc35c612c72afc248fdc52fcb907610fbca9ea237579a95f33eedc435553?nocache=1

**Comment by Joshua-Noakes1** [comment]
Seems to be working all well, thank @Awire9966

**Comment by Awire9966** [comment]
> Seems to be working all well, thanks @Awire9966

np
